### ISSUE TITLE
analytics.js and key

### ISSUE THREAD

**Issue by mmahalwy** [nfl/react-metrics#10]
Hey, using Segment as suggested in the docs, how did you figure out getting your Segment write key into the vendors?

Thanks!

**Comment by taak77** [comment]
Hi, thanks for your interest in this library.

Trying to understand your question,
if you mean analytics vendor name by `key`,

In the case of Google Analytics,

key name is defined here
https://github.com/segment-integrations/analytics.js-integration-google-analytics/blob/master/lib/index.js#L35

which is set here
https://github.com/segmentio/analytics.js-integration/blob/master/lib%2Findex.js#L51

and used here
https://github.com/segmentio/analytics.js-core/blob/master/lib%2Fanalytics.js#L132

and would be used in your vendor file like this example
https://github.com/nfl/react-metrics/blob/master/examples%2Fvendors%2FGoogleAnalytics.js#L86

Does it answer your question?

**Comment by mmahalwy** [comment]
@taak77 apologize for lack of clarity. I guess my challenge is, I use Segment so I don't have to write and store my individual tools' keys. One key, Segment's, and it will push to everything. I was wondering if you have a suggestion for how to set it for analytics.js given many of the community has been complaining about a AMD solution https://github.com/segmentio/analytics.js/issues/398 versus the getting your own analytics.js file via their script and your key.

**Comment by taak77** [comment]
@mmahalwy ok, i think i understand your question now.

If you bundle analytics.js, you need to call `analytics.initialize` manually and pass the configuration by yourself, so you can't take advantage of Segment console to enable/disable integrations w/o code change.

if you load analytics.js from their CDN with your key, analytics.js will automatically reflects the integration settings from your Segment console.

So i would load analytics.js from their CDN.
