### ISSUE TITLE
Why is IE 10 the minimum browser requirement?

### ISSUE THREAD

**Issue by jedmao** [nfl/react-metrics#12]
What feature demands IE 10 that IE 9 doesn't have?

**Comment by potench** [comment]
So you're saying this should work in IE9?

**Comment by jedmao** [comment]
I didn't say that. I'm asking what the feature is that supposedly doesn't work in IE 9 so that we can make a business decision whether or not to use this or if we need a polyfill of some kind.

**Comment by potench** [comment]
Ah I see. It should work in IE9 as it's compiling to ES5. Clone the repo and run the example project in IE9 to see.

**Comment by potench** [comment]
@jedmao - I just ran the example project in IE9 without any errors. If you're using a VM to run IE9, you can update the `package.json` script with:
```
"examples": "webpack-dev-server --config examples/webpack.config.js --host YOUR_NETWORK_NAME --content-base examples --inline",
```

Replace `YOUR_NETWORK_NAME` with your IP Address or network name so you can hit the example page from your VM. Hope this helps.

**Comment by potench** [comment]
More to the point of your question: 

> Why is IE 10 the minimum browser requirement?

There was no specific technical limitation to supporting IE9. We developed this component to our internal support standards which (at this time) are IE10+ based on the implementation and maintenance costs of supporting IE9 across the board.

**Comment by jedmao** [comment]
Tasks for the detail. I think we can take it from here.
