### ISSUE TITLE
Should have option to have event bubble to parent link

### ISSUE THREAD

**Issue by mmahalwy** [nfl/react-metrics#17]
If I have, for example:
```
<a data-metrics-event-name="SomeEvent">
  <img src="..." />
</a>
```

and the user clicks on the image... the events won't register because the `event.target` is the image and has no `data-metrics`. There should be an option or something to fix this to have it bubble to data-metrics. I have this problem here:
```
return (
      <Link to={this.getPath()}>
        <h4>
          <u
            data-metrics-event-name="ActivityRow:Title:Click"
            data-metrics-activity-id={activity.id}>
            {/* LEGACY */}
            {activity.infoName || activity.name}
          </u>
        </h4>
      </Link>
    );
```
which is bad cause the `<u>` tag should not have the event names.

**Comment by taak77** [comment]
@mmahalwy,

I agree that it'd be nice if it can bubble up, which is easy to achieve by traversing up the DOM tree,
but since it's using event delegation from the root element, this traversal happens every time in every node when users click any elements, which most of the times ends up traversing up to the root element for nothing and i want to avoid that for perf reason. Please let me know if you have some ideas.

**Comment by mmahalwy** [comment]
@taak77 it's certainly an unsolved problem I feel. 
There might be a few ways:
1. Reactjs doesn't register clicks on mobile unless it has style `cursor: pointer` anyways, so that might be a good guide?
2. A data attribute for the node to use. For example `a.link > img` and the image is clicked, you'd have something like `data-element=".link"` on the anchor tag, which will be found once bubbled up
3. Have a container component that would have the event data, and any clicks to any of it's children would traverse to the component. `<MetricsElement><img /></MetricsElement>`

Just some thoughts. What do you think?

**Comment by taak77** [comment]
@mmahalwy, 
thanks for the ideas, yeah, we'll need some hint to limit the scope, which i wasn't too excited about.
But i feel we'll end up having something like option 3 you described and register click event delegation listener on each `<MetricsElement>`.

**Comment by mmahalwy** [comment]
Yeah which doesn't sound too bad. You can always support either or - just developer's preference
