### ISSUE TITLE
Reduce `polyfill.js` or remove all together

### ISSUE THREAD

**Issue by andykenward** [nfl/react-metrics#19]
I have noticed you are [importing](https://github.com/nfl/react-metrics/blob/master/src/index.js#L1) the [polyfill.js](https://github.com/nfl/react-metrics/blob/master/src/polyfill.js) into this package which bloats the file size when you use it in a project. I would much prefer giving people the option to use their own polyfills if they need them for their projects.

At least remove the [promise](https://github.com/nfl/react-metrics/blob/master/src/polyfill.js#L4) polyfill which adds 10kb. Add to the readme about the need to use your own promise polyfill.

**_side note_** 
_Ideally there will be better support for having ES5 and ES2015 npm modules together. Something like [rollup](https://github.com/rollup/rollup/wiki/jsnext:main) has. So once webpack v2 is released then we can all do [tree-shaking](http://www.2ality.com/2015/12/webpack-tree-shaking.html)._

**Comment by taak77** [comment]
@andykenward, thanks for the suggestion.
Will work on removing them.
