### ISSUE TITLE
metrics decorator and unit-testing

### ISSUE THREAD

**Issue by KnisterPeter** [nfl/react-metrics#21]
Hi,

the metrics decorator is not very unit-test friendly. It allows mounting a component only once and remembers the instance on a global variable relative to the module.
There is no API to reset the instances right now, isn't it? Not even unmounting will help.

Please add a sane way to clear test cases.

**Comment by taak77** [comment]
@KnisterPeter, 

unmounting component should reset the instance count and that's how i do in my unit test.
https://github.com/nfl/react-metrics/blob/master/src/react/metrics.js#L97-L103

**Comment by KnisterPeter** [comment]
Thanks, I'll give it a try.

**Comment by KnisterPeter** [comment]
Unfortunately this does not work as expected.
As a side note: We do not decorate our root component. This is, because we have two applications sharing the root-component, therefore we put the metrics decoration at the upmost 'root' of each application. But from my understanding it should work that way too.

**Comment by potench** [comment]
Can you clarify what you are expecting and what the actual result is? Is the `metricsInstance` not destroying and global `instances` not splicing? You sure your `componentWillUnmount` is being called?

**Comment by taak77** [comment]
@KnisterPeter, i'll take a look. I think it's better to define instance registry as class property so that you could potentially have 2 root metrics HOC for both tree A and B with different configurations.

**Comment by taak77** [comment]
@KnisterPeter, i just checked and seems working for me with react-router.
In the following setup, where `AppBWithMetrics` and `AppCWithMetrics` are wrapped with `metrics`,
when i navigate from `/app-b` or `app-c` to `/app-a`, `metrics` is unmounted and instance registry is reset to 0. When i navigate from `/app-b` to `/app-c`, unmount from `AppBWithMetrics` and mount to `AppCWithMetrics` and instance registry is kept intact as well.

```
ReactDOM.render((
    <Router history={hashHistory}>
        <Route path="/" component={MonoApp}>
            <Route path="app-a" component={AppA}/>
            <Route path="app-b" component={AppBWithMetrics}/>
            <Route path="app-c" component={AppCWithMetrics}/>
            <Route path="*" component={NotFound}/>
        </Route>
    </Router>
), document.getElementById("example"));
```

Let me know if you have a different setup where you can reproduce the issue.

**Comment by taak77** [comment]
Closing.

**Comment by mmahalwy** [comment]
Maybe a config to turn off the check for multiple instances could get tihngs to go by. For example, I have file:

```
import React from 'react';
import { metrics } from 'react-metrics';

const Container = ({ children }) => React.cloneElement(children, {});

const config = {
  pageViewEvent: 'pageLoad',
  vendors: [
    {
      api: {
        name: 'Segment',
        pageView() {
          return false;
        },
        track() {
          return false;
        },
        user() {
          return false;
        }
      }
    }
  ]
}

export default metrics(config, {suppressTrackBindingWarning: true})(Container);
```

An option to allow more than one instances would clear my head from forgetting to unmount. Just a thought :)
