### ISSUE TITLE
customParams in event tracking

### ISSUE THREAD

**Issue by Mirodil** [nfl/react-metrics#25]
Is it possible add data from `customParams` to `track` event type?

**Comment by taak77** [comment]
@Mirodil - `customParams` gets merged into `pageDefaults` if specified and if you pass `true` as the 3rd argument of `this.context.metrics.track`, `pageDefaults` will gets merged into the `track` params.
Example: https://github.com/nfl/react-metrics/blob/master/examples/no-router-lib/basic/page.js#L19

**Comment by Mirodil** [comment]
That is cool, what about if it uses with `data` attribute?

**Comment by taak77** [comment]
@Mirodil - that's not currently supported although should be easy to add that feature.
i can add support for optional `data-merge-pagedefaults="true"` attr, does that sound good to you?

**Comment by Mirodil** [comment]
yes, sure. it will be great.

**Comment by taak77** [comment]
@Mirodil - can you check PR #26? If it looks good to you, I can merge it.

**Comment by Mirodil** [comment]
yes, looks cool.

**Comment by taak77** [comment]
@Mirodil - 2.2.1 released, please give it a try.

**Comment by Mirodil** [comment]
thank you
