### ISSUE TITLE
Cannot install latest react-metrics-2.2.1

### ISSUE THREAD

**Issue by maheshtracxn2016** [nfl/react-metrics#27]
Error message
npm install --save react-metrics
npm ERR! fetch failed https://registry.npmjs.org/react-metrics/-/react-metrics-2.2.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/react-metrics/-/react-metrics-2.2.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404

**Comment by taak77** [comment]
@maheshtracxn2016 Thanks for reporting this. Not sure what went wrong with v2.2.1 since publishing was successful. I just re-published as v2.2.2 and it should work.
