### ISSUE TITLE
enabled=false in config not working

### ISSUE THREAD

**Issue by Mirodil** [nfl/react-metrics#28]
There is logic in the code, if there is no any venders disable metrics with `enabled:false`, but after this it returns error `react-metrics: 'pageView' api needs to be defined for automatic page view tracking.` from `https://github.com/nfl/react-metrics/blob/master/src/react/metrics.js#L143`. I guess, this line of code should check whether metrics enabled or not.

**Comment by potench** [comment]
Looks like `createMetrics` uses this option here:
https://github.com/nfl/react-metrics/blob/e76ad50c3d95037b8fc68cbbd52e8ea65521f33d/src/core/createMetrics.js#L114-L116

I imagine we could include it here https://github.com/nfl/react-metrics/blob/master/src/react/metrics.js#L129 with 
```
        if (!metricsInstance.enabled) {
            return;
        }
```

**Comment by Mirodil** [comment]
yes it will be great

**Comment by taak77** [comment]
@Mirodil please try 2.2.3
