### ISSUE TITLE
Accessibity issues: does not handle on enter hit like click

### ISSUE THREAD

**Issue by Mirodil** [nfl/react-metrics#29]
A user can navigate using tab and hit enter as well as user can use mouse click (accessibility). What if we add handler for enter key after click event 'https://github.com/nfl/react-metrics/blob/master/src/core/useTrackBindingPlugin.js#L32'?

**Comment by taak77** [comment]
@Mirodil `click` event will be fired when hitting enter key on the focused element.

**Comment by Mirodil** [comment]
Thanks you
