### ISSUE TITLE
Namespace PropTypes

### ISSUE THREAD

**Issue by chrisknu** [nfl/react-metrics#36]
Import { PropTypes } from 'react-metrics' may collide with the PropTypes from 'https://www.npmjs.com/package/prop-types'

Suggest namespacing to this package

**Comment by coluccini** [comment]
You can avoid collides by importing with an alias

```Import { PropTypes as MetricsPropTypes } from 'react-metrics'```

**Comment by LGCambra** [comment]
Closed by #38 and #42.
