### ISSUE TITLE
Warning when accessing PropTypes via main package

### ISSUE THREAD

**Issue by wmartins** [nfl/react-metrics#39]
Hey guys, first of all, thank you for this awesome library.

I'm opening this issue because we noticed a common problem when using this library with `React v15.5.0`.

Currently, `react-metrics` is displaying the following warning on console:

```
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
```

As of React v15.5.0, `PropTypes` has its own package, and now it shows a deprecation warning when using `PropTypes` directly from `React` package.

Related: https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#new-deprecation-warnings

Just as a quick reference, this code now shows a warning:

```javascript
import { PropTypes } from 'react';
```

Now, the "correct" way of using `PropTypes` is via [`prop-types`](https://www.npmjs.com/package/prop-types) package.

```javascript
import PropTypes from 'prop-types';
```

Do you guys mind if I open a pull request to use this new `prop-types` package instead of "main" `PropTypes`?

Thank you!

---

Related: #38

**Comment by jamsea** [comment]
@wmartins that would be great. We haven't upgraded to React v15.5.0 yet but I'll gladly review a PR for including the prop-types package 👍

**Comment by wmartins** [comment]
Thank you @jamsea, I'll provide a PR for that soon.

**Comment by wmartins** [comment]
Hey @jamsea, will you guys publish a new npm version for that?

Thank you!

**Comment by jamsea** [comment]
@wmartins published 👍

**Comment by wmartins** [comment]
@jamsea Thank yoU!
