### ISSUE TITLE
SVG click in IE logs a 'Unable to get property 'attributes' of undefined or null reference' console error

### ISSUE THREAD

**Issue by nmoore93** [nfl/react-metrics#45]
Hi, this issue only occurs in IE. When clicking on an SVG icon in IE that is to be tracked through the use of <MetricsElement>, or is in a section to be tracked, an error is logged in the console stating that 'Unable to get property 'attributes' of undefined or null reference'.

It seems that element.parentElement is not supported for SVG elements in IE so needs to also use element.parentNode.

I have a PR ready to add as well which I will link to this issue.

Thanks.

**Comment by nmoore93** [comment]
@jamsea Hi, sorry to bug you I was just wondering if yourself (or anyone else) were able to recreate this and if the linked PR #46 was good?

Thanks

**Comment by potench** [comment]
@nmoore93 thanks, this has been published in 2.3.2
