### ISSUE TITLE
Does this support Average time on page?

### ISSUE THREAD

**Issue by 416serg** [nfl/react-metrics#57]
Essentially I am looking to build out my own metrics system to track performance of a widget embedded externally from my main application. Currently, the way that it works is I have an iFrame with a specific path for each widget and then I use Google Analytics's API to get data on those paths (pageviews and average time on page) but it's a pain in the 🍑

I am looking for a solution where I can build out a component that tracks it's own performance without relying on a URL path - ie if someone embeds my widget somewhere without an iFrame, I want the component to be able to track it's own data and push it down to my DB.

I can imagine I'd be able to do so for pageviews but I don't see any documentation on average time on page.

**Comment by potench** [comment]
i think you are looking for Imperative Custom Event Tracking https://github.com/nfl/react-metrics/blob/master/README.md#imperative-custom-event-tracking

Doesn’t require a URL, just custom data - you’ll still want to use some kind of identifier so you know what you’re tracking though, URLs are great for that. 

Feel free to reopen this if I’m wrong; if you do try to share what you’ve already attempted and why it doesn’t work for you.
