### ISSUE TITLE
Custom vendor API methods require an argument to be passed

### ISSUE THREAD

**Issue by ntibbles** [nfl/react-metrics#59]
When creating a custom method (as outlined here: https://github.com/nfl/react-metrics/blob/master/docs/Guides.md#api) the method always expects an argument to be passed, whether or not the method expects one. To recreate the issue, use the example in the docs, and use the metrics context object to call the method (i.e - this.context.metrics.someMethod()).
When no argument is passed, the method doesn't get called, but if anything is passed, the method gets called.

**Comment by potench** [comment]
Forgot to close this. Solved in #60
