### ISSUE TITLE
Get config from props - metrics(config)

### ISSUE THREAD

**Issue by Pranab16** [nfl/react-metrics#62]
Is there a way to get config from props for example in case of GoogleAnalytics I want to get trackingId from props.

**Comment by potench** [comment]
Yeah it's possible to configure metrics wherever. However, typically, you'd configure it at the top level of your app where you would not need to pass `trackingId` down as a prop.  

https://github.com/nfl/react-metrics#metrics-api-outside-a-react-component
```
import {createMetrics} from "react-metrics";

class YourComponent extends React.Component {
    componentDidMount() {
        const metrics = createMetrics({
            trackingId: this.props.trackingId
        });
    }
}

```

Closing this issue, feel free to reopen with some code sample of what you've tried if this doesn't answer the question.
